### PR TITLE
Add Kenwood sentence PKLSH and expand gitignore to ignore .venv for c…

### PR DESCRIPTION
**Pull request by erinn**
…onvenience.

# pynmeagps Pull Request Template

## Description

Add a Kenwood Proprietary sentence $PKLSH. Only public documentation was used to derive the structure of the sentence. 

Also, and much smaller, added .venv to .gitignore for convenience.

## Testing

Please test all changes, however trivial, against the supplied unittest suite `tests/test_*.py` e.g. by executing the `tests/testsuite.py` module or using your IDE's native Python unittest integration facilities. Please describe any test cases you have amended or added to this suite to maintain >= 99% code coverage.

Tests were run using pytest, no failures and there is no real codecov for the additions I made as far as I can tell.

## Checklist:

- [X] My code follows the style guidelines of this project (see `CONTRIBUTING.MD`).
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have made corresponding changes to the documentation.
- [X] (*if appropriate*) I have added test cases to the `tests/test_*.py` unittest suite to maintain >= 99% code coverage.
- [X] I have tested my code against the full `tests/test_*.py` unittest suite.
- [X] My changes generate no new warnings.
- [X] Any dependent changes have been merged and published in downstream modules.
- [X] I understand and acknowledge that the code will be published under a BSD 3-Clause license.

### CODE REVIEW

**Comment by erinn** [comment]
I believe this is ready for review. There is one oddity which I am unsure of. The time field is returned from the radios not as a float but an int, you can see this in the test case. It's possible Kenwood has a bug here, perhaps they fixed it in newer firmware versions. For my purposes time coming back "" is just fine, but it is odd.

**Comment by semuadmin** [comment]
Hi @erinn This looks fine, but I'll have to take your word for the test output as I don't have a suitable device to hand (I presume this relates to JVC's in-car GNSS systems?). Purely for the record, can you clarify which public domain source you used for the payload definition? Thanks.

**Review by semuadmin — COMMENTED** [review]
Re. `testParsePKLSH`; does your device only ever output blanks in the `time` field? Do you have any example of non-blank output? Can you share the public domain payload definition please? Thanks.

**Comment by erinn** [comment]
These are Kenwood radios that are transmitting their location over the air via, well basically a 1200 to 2400 baud modem. This is referred to as FleetSync (bottom of page: https://mra-raycom.com/articles/signaling-methods-for-radio-systems/). Motorola has their own version of this MDC-1200. 

Kenwood's manuals describe the general construct of the sentence here: http://www.repeater-builder.com/kenwood/pdfs/tk-8180-field-prg-man.pdf page 96 of the manual (page 102 of the PDF overall). You can also view examples here: https://github.com/ncssar/radiolog/blob/master/radiolog.py#L1472 and the rest was just deductive reasoning. 
As you can see from the manual they have a number of different outputs they are able to do PKLDS, PKLID. For the moment I'm only interested in PKLSH but others can be implemented.

As it states in the manual, this is supposed to consist of a $GPGLL with a device ID and fleet ID added on. However, their GPGLL also lacks the 'mode indicator' field (deriving the construct from here: https://docs.novatel.com/OEM7/Content/Logs/GPGLL.htm#NMEAPositioningSystemModeIndicator), see test code for a real sentence output.

To be clear it DOES output a time, it just DOES NOT output a time with a '.' in it, at least as far as I have seen, this was mentioned in the initial comment, I am unsure if this is a bug on Kenwood's part or what. Doesn't mean it NEVER does :).

**Comment by semuadmin** [comment]
Hi again @erinn 

Assuming your test payload is representative, this may actually require a tweak to the `time2utc()` method in `nmeahelpers.py` (_and, as a consequence, a tweak to your test case_) to process a time string which doesn't have the decimal seconds component (by assuming the decimal component is ".00") - see illustrations below.  If I do that, the utc time comes out as "01:22:12" - does that sound appropriate for your test payload?

```
def time2utc(times: str) -> datetime.time:
    """
    Convert NMEA Time to UTC datetime.

    :param str times: NMEA time hhmmss.ss
    :return: UTC time hh:mm:ss.ss
    :rtype: datetime.time
    """

    try:
        if len(times) == 6: # decimal seconds is omitted
            times = times + ".00"
        utc = datetime.strptime(times, "%H%M%S.%f")
        return utc.time()
    except (TypeError, ValueError):
        return ""
```

```
def testParsePKLSH(self):  # Proprietary JVCKenwood message
        res = NMEAReader.parse(self.messagePKLSH)
        self.assertEqual(
            str(res),
            "<NMEA(PKLSH, lat=38.85555, NS=N, lon=-94.7990283333, EW=W, time=01:22:12, status=V, fleetId=100, deviceId=1202)>",
        )
```

Not sure why they didn't simply implement the same format as a normal GPGLL message but, as you say, may be a bug.

**Comment by erinn** [comment]
That's also a possibility. Let me gather more data and I'll get back to you.

**Comment by semuadmin** [comment]
Hi @erinn Any more thoughts on this?

**Comment by erinn** [comment]
Still in the works, wheels turn slowly here. If you like I can close the PR and reopen when I’ve got more details. On Aug 21, 2022, at 01:53, SEMU Admin ***@***.***> wrote:﻿
Hi @erinn Any more thoughts on this?

**Comment by erinn** [comment]
I can confirm that there is no decimal, tested across multiple radios and firmware versions. I believe you are the only one that can reopen this PR at this point, so if you'd do that and merge it with the changes you discussed that'd be much appreciated.

**Comment by erinn** [comment]
And a bit of further data, I am able to get the radios to output GPRMC GPGGA and GPGLL sentences in addition to their proprietary sentences (PKLDS, PKLSH). NONE of the sentences have a float for time. Again not saying Kenwood isn't doing things incorrectly, they may well be, but I believe the code you mentioned is a reasonable workaround.

**Pull request merged**
